import type { SkillCardDto } from '@agent-skills/types';

export const CATEGORIES = [
  'All',
  'Coding',
  'Writing',
  'Data Analysis',
  'DevOps',
  'Security',
  'Git',
  'Automation',
] as const;

export const MOCK_SKILLS: SkillCardDto[] = [
  {
    id: 'skill_terraform_guardrails',
    slug: 'code-reviewer-pro',
    name: 'Code Reviewer Pro',
    shortDescription: 'Advanced code review with security scanning and best practices analysis',
    thumbnailUrl: null,
    creatorName: 'CodeMaster',
    installCount: 1243,
    averageRating: 4.7,
    supportedAgents: ['Claude', 'Codex'],
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    tags: ['Security', 'Quality', 'Best Practices'],
    categories: ['Coding', 'Security'],
  },
  {
    id: 'skill_pr_review',
    slug: 'git-flow-expert',
    name: 'Git Flow Expert',
    shortDescription: 'Automate git workflows with intelligent branch management',
    thumbnailUrl: null,
    creatorName: 'DevOps Team',
    installCount: 2156,
    averageRating: 4.6,
    supportedAgents: ['Codex'],
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
    tags: ['Git', 'Automation', 'Workflow'],
    categories: ['Git', 'Automation'],
  },
  {
    id: 'skill_sales_prospect',
    slug: 'content-writer-ai',
    name: 'Content Writer AI',
    shortDescription: 'Generate blog posts, docs, and marketing copy with your brand voice',
    thumbnailUrl: null,
    creatorName: 'WriterStudio',
    installCount: 892,
    averageRating: 4.4,
    supportedAgents: ['Claude'],
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    tags: ['Writing', 'SEO', 'Brand'],
    categories: ['Writing'],
  },
  {
    id: 'skill_log_triage',
    slug: 'prod-log-triage',
    name: 'Prod Log Triage',
    shortDescription: 'Summarize logs, identify root causes, and propose fixes with confidence levels',
    thumbnailUrl: null,
    creatorName: 'SRE Guild',
    installCount: 2660,
    averageRating: 4.4,
    supportedAgents: ['Claude', 'Codex'],
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
    tags: ['DevOps', 'SRE', 'Debugging'],
    categories: ['DevOps'],
  },
];

